### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by Sephiroth87** [RedPlumber/SwiftProject#1]
The problem is the app will load frameworks from the bundle's Frameworks folder, but the pod's frameworks are now inside Frameworks/MyFramework.framework, so they are not found...Maybe there's a way to specify a different path to load them...

**Comment by francescopetrungaro** [comment]
Have a look at the Objective-C pod section https://github.com/RedPlumber/SwiftProject/tree/Develop#objective-c-pod

I specified what I believe is the right path in the build settings of the app target under FRAMEWORK_SEARCH_PATHS

**Comment by francescopetrungaro** [comment]
With the same configuration everything is working on master branch. For some reason that's not the case on develop where I use an additional pod.

**Comment by Sephiroth87** [comment]
You are not accessing a framework that wasn't loaded in memory on master, it would crash if you tried to use TSCurrencyTextField.

![screen shot 2015-04-27 at 12 28 50](https://cloud.githubusercontent.com/assets/1456711/7345847/fe625a8e-ecd8-11e4-89d0-848fca9a73a0.png)

This is the problem, frameworks are only loaded from the root folder by default, so MyFramework is loaded, and the others inside are not...

**Comment by francescopetrungaro** [comment]
I use TSCurrencyTextField framework, check storyboard for app and extension.

**Comment by francescopetrungaro** [comment]
Fixed
